export type Jurisdiction = "US_Federal" | "US_State" | "UK" | "India" | "General";
export type AreaOfLaw =
  | "contract"
  | "tort"
  | "employment"
  | "ip"
  | "criminal"
  | "constitutional"
  | "corporate";
export type ClientPosition = "plaintiff" | "defendant" | "appellant" | "respondent";
export type BriefStrength = "strong" | "moderate" | "weak";

export interface CaseInput {
  title: string;
  jurisdiction: Jurisdiction;
  area_of_law: AreaOfLaw;
  facts: string;
  client_position: ClientPosition;
  desired_outcome: string;
  key_issues?: string[];
}

export interface CaseReference {
  case_name: string;
  citation: string;
  relevance: string;
  /** true = LLM-generated plausible reference, NOT verified as real */
  is_synthetic: boolean;
}

export interface LegalArgument {
  heading: string;
  thesis: string;
  supporting_points: string[];
  case_references: CaseReference[];
  counterargument: string;
  rebuttal: string;
}

export interface LegalBrief {
  title: string;
  jurisdiction: string;
  executive_summary: string;
  statement_of_facts: string;
  issues_presented: string[];
  arguments: LegalArgument[];
  counterarguments_summary: string;
  recommended_strategy: string;
  risk_assessment: {
    strength: BriefStrength;
    key_vulnerabilities: string[];
    confidence: number; // 0-100
  };
  disclaimer: string;
}

export const JURISDICTION_LABELS: Record<Jurisdiction, string> = {
  US_Federal: "US Federal",
  US_State: "US State",
  UK: "United Kingdom",
  India: "India",
  General: "General / Unspecified",
};

export const AREA_LABELS: Record<AreaOfLaw, string> = {
  contract: "Contract",
  tort: "Tort",
  employment: "Employment",
  ip: "Intellectual Property",
  criminal: "Criminal",
  constitutional: "Constitutional",
  corporate: "Corporate",
};

export const POSITIONS: ClientPosition[] = [
  "plaintiff",
  "defendant",
  "appellant",
  "respondent",
];

export const STANDARD_DISCLAIMER =
  "This brief was generated by an AI model for demonstration purposes. Case references may be synthetic. Do not use for actual legal proceedings without review by a qualified attorney.";
