import type { BiasReport, QuestionBank, ScreeningResult } from "./types";

/** Builds the "Export Full Report" Markdown document from whatever parts of
 * the report exist. Pure function — safe to call from the client. */
export function buildMarkdownReport(
  result: ScreeningResult,
  bias: BiasReport | null,
  questions: QuestionBank | null
): string {
  const lines: string[] = [];

  lines.push("# Candidate Screening Report");
  lines.push("");
  lines.push(`_Generated ${new Date().toISOString()} by Recruitment Screener (local Ollama)._`);
  lines.push("");

  // ── Score report ──
  lines.push("## 1. Score Report");
  lines.push("");
  lines.push(`**Overall match:** ${result.overall_score}/100 — **${result.verdict}**`);
  lines.push("");
  lines.push(result.summary);
  lines.push("");
  lines.push("### Criteria breakdown");
  lines.push("");
  lines.push("| Dimension | Score | Rationale |");
  lines.push("|---|---:|---|");
  for (const c of result.criteria) {
    lines.push(`| ${c.name} | ${c.score} | ${c.rationale.replace(/\|/g, "\\|")} |`);
  }
  lines.push("");
  lines.push("### Strengths");
  lines.push("");
  for (const s of result.strengths) lines.push(`- ${s}`);
  lines.push("");
  lines.push("### Gaps");
  lines.push("");
  for (const g of result.gaps) lines.push(`- ${g}`);
  lines.push("");

  // ── Bias check ──
  lines.push("## 2. Bias Check");
  lines.push("");
  if (!bias) {
    lines.push("_Bias check was not run._");
  } else if (bias.flags.length === 0) {
    lines.push("✅ **No bias signals detected.** Overall risk: low.");
  } else {
    lines.push(`⚠️ **Overall risk: ${bias.overall_risk}** — ${bias.flags.length} flag(s) raised.`);
    lines.push("");
    for (const flag of bias.flags) {
      lines.push(`### ${flag.type.replace(/_/g, " ")} — ${flag.severity} severity`);
      lines.push("");
      lines.push(flag.detail);
      lines.push("");
      lines.push(`> **Recommendation:** ${flag.recommendation}`);
      lines.push("");
    }
  }
  lines.push("");

  // ── Interview kit ──
  lines.push("## 3. Interview Kit");
  lines.push("");
  if (!questions) {
    lines.push("_Interview kit was not generated._");
  } else {
    const sections: [string, keyof QuestionBank][] = [
      ["Technical", "technical"],
      ["Behavioural", "behavioural"],
      ["Culture Fit", "culture"],
    ];
    for (const [title, key] of sections) {
      lines.push(`### ${title}`);
      lines.push("");
      questions[key].forEach((q, i) => {
        lines.push(`${i + 1}. **${q.question}**`);
        lines.push(`   - _Why this question:_ ${q.rationale}`);
        lines.push(`   - _What good looks like:_ ${q.what_to_look_for}`);
      });
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_This report was generated by a local LLM. Scores, bias flags, and questions are directional aids for a human recruiter — not automated hiring decisions._"
  );
  lines.push("");

  return lines.join("\n");
}

/** Trigger a browser download of the given Markdown text. */
export function downloadMarkdown(markdown: string, filename: string): void {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
